---

- hosts: all
  tasks:
  - name: "Download Netdata"
    get_url:
      url: "https://my-netdata.io/kickstart.sh"
      dest: "/tmp/kickstart.sh"
      mode: +x
  
  - name: "Install Netdata package"
    command: "/tmp/kickstart.sh --stable-channel --disable-telemetry --dont-wait --no-updates --native-only"